services:
   ipfs_host:
      image: ipfs/kubo
      container_name: ipfs
      restart: unless-stopped
      ports:
         - "4001:4001"
         - "5001:5001"
         - "8080:8080"
      volumes:
         - ./ipfs_data:/data/ipfs
      logging:
         driver: "json-file"
         options:
            max-size: "10m"
            max-file: "3"
   postgres:
      image: postgres:latest
      container_name: postgres
      restart: unless-stopped
      environment:
         POSTGRES_USER: username
         POSTGRES_PASSWORD: password
         POSTGRES_DB: nft_service
      ports:
         - "5432:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data
      logging:
         driver: "json-file"
         options:
            max-size: "10m"
            max-file: "3"
volumes:
   postgres_data:
